### PR TITLE
Basic Database Structure

### LINKED ISSUE #1: Database Integration
For database, we decided to use PostgreSQL without any ORM.

We need to create a service in Nest JS to communicate with database.

For now, the database will consist:
- User information
    - Name
    - Hashed Password
    - Accessible raffle IDs
    - Other necessary data (configuration etc)
- Raffles
    - Id
    - Other necessary data (will be discussed later)

### PR DESCRIPTION
**Pull request by Utkub24**
- [ ] I have not added anything unrelated of this PR to the PR message (I had to make the joke sry)

Closes #1 

I (@HuseyinSimsek7904 not @Utkub24) got bored so I decided to create database services for the project. I did not have 5 PRs that are ready and waiting for review, so you are completely right to say that I should not be bored.

## Explanation of the contents of the PR
The PR has two main parts: the makefile and interface/service/controllers for the database. The makefile is updated so that the developer can generate a valid database for experiments and tests. The code changes contain new interfaces and other database management programs for the database entries types: `user`, `raffle` and `participant`. There is also `formQuestion` interface which is used for storing the information of the form questions that the raffle table contains.

## Future plans
Currently we do not have any plans. We should discuss this as soon as possible.

## Notes
- This PR contains breaking changes about the .env file. Please update your it after this PR according to the wiki entry.
- All of the raffles that the makefile generates have an empty form field.
- I can not add @Utkub24 as a reviewer as he is the owner of the PR, but I want him to review as well.

### CODE REVIEW

**Comment by HuseyinSimsek7904** [comment]
Please before continuing your work @Utkub24, refresh your _.env_ file according to the wiki entry. I had to update its variable names so that both the Makefile and the nestJS application could use it without weird name conventions and redefinitions.

**Comment by HuseyinSimsek7904** [comment]
@Utkub24 Why would you remove the checklist before converting the PR from a draft? Now we have to manually copy-paste them after we are done.

Let's not remove these checklists before the PR is ready.

**Comment by Utkub24** [comment]
> copy-paste

Is this intentional?

**Comment by HuseyinSimsek7904** [comment]
> > copy-paste
> 
> Is this intentional?
> 
> 

'course it is.

**Comment by ErtyumPX** [comment]
I checked the files a bit, as for follow-up suggestions, we need to have to routes to be used in the client side that:
- Checks if a raffle ID is valid or not, if so, checks the senders IP address and determines if they have submitted before, if so, we will send a special respons telling us in the front-end to show the user 'Thanks for submitting!' component.
- Gets the raffle data/information which needs to be stripped from confidential data, like we may want to exclude author info, any participant relation etc. if there is any

**Comment by ErtyumPX** [comment]
Will also check the PR very soon, things seem pretty cool though, good job :+1:

**Comment by ErtyumPX** [comment]
Also for follow-up, we do not have routes for registering participants, and creating new raffles

**Review by ErtyumPX — APPROVED** [review]
LGTM!!!!

**Pull request merged**
